#!/bin/bash
# Parses a local compose's repos
#set -x

if [ -n "$1" ]; then
  MAJOR=$1
else
  echo "Major version not specified"
  exit 1
fi

if [ -f /usr/bin/dnf4 ]; then
  SAFEDNF=/usr/bin/dnf4
else
  SAFEDNF=/usr/bin/dnf
fi

export RLVER=$MAJOR
source common

drop="${PREPOPDROP}"
current=$(pwd)
compose_dir="${COMPOSE_BASEDIR}/${MAJOR}/latest-Rocky-${MAJOR}/compose"

pushd "${compose_dir}" || { echo "Could not change directory"; exit 1; }
/usr/bin/python3 "${current}/prepopulate_parser.py" --pungi --version ${RLVER}
ret_val=$?
popd || { echo "Could not change back..."; exit 1; }

if [ "$ret_val" -ne "0" ]; then
  echo "There was an error running through the parser."
  exit 1
fi

echo "File located at: $drop"
