#!/bin/bash
source common

if [ ! -f "/usr/bin/pungi-koji" ]; then
  echo "You must have pungi installed."
  exit 1
fi

VER="${RLVER}"
BRANCH="r${VER}"
REPO="${GIT_URL}/rocky/pungi-rocky.git"

CMD="/usr/bin/pungi-koji --production --no-latest-link --just-phase init --config rocky.conf --compose-dir /var/tmp/composes/ --label RC-${VER}"

git clone ${REPO} -b ${BRANCH} /var/tmp/pungi
pushd /var/tmp/pungi
${CMD}
popd
