#!/usr/bin/env python3

from common import *
import argparse
from util import Checks
from util import RepoSync

rlvars = rldict['9']
r = Checks(rlvars, config['arch'])
r.check_valid_arch()

a = RepoSync(rlvars, config, repo="BaseOS")
print(a.sync())
