#!/usr/bin/env python3

# This is a testing script to ensure the RepoSync class is working as intended.

from common import *
import argparse
from util import Checks
from util import RepoSync

rlvars = rldict['9']
r = Checks(rlvars, config['arch'])
r.check_valid_arch()

#a = RepoSync(rlvars, config, major="9", repo="ResilientStorage", parallel=True, ignore_debug=False, ignore_source=False)
a = RepoSync(rlvars, config, major="9", repo="BaseOS", parallel=True, ignore_debug=False, ignore_source=False, hashed=True)
a.run()
