---
'10':
  fullname: 'Rocky Linux 10.0'
  revision: '10.0'
  rclvl: 'RC1'
  major: '10'
  minor: '0'
  profile: '10'
  disttag: 'el10'
  code: "Red Quartz"
  bugurl: 'https://bugs.rockylinux.org'
  checksum: 'sha256'
  fedora_major: '20'
  allowed_arches:
    - x86_64
    - aarch64
    - ppc64le
    - s390x
  provide_multilib: True
  project_id: 'e7b83c0a-b514-4903-b739-6943bbb307f7'
  repo_symlinks:
    NFV: 'nfv'
  renames:
    all: 'devel'
  all_repos:
    - 'all'
    - 'BaseOS'
    - 'AppStream'
    - 'CRB'
    - 'HighAvailability'
    - 'ResilientStorage'
    - 'RT'
    - 'NFV'
    - 'SAP'
    - 'SAPHANA'
    - 'extras'
    - 'plus'
  structure:
    packages: 'os/Packages'
    repodata: 'os/repodata'
  iso_map:
    xorrisofs: True
    iso_level: False
    images:
      dvd:
        disc: True
        variant: 'AppStream'
        repos:
          - 'BaseOS'
          - 'AppStream'
      minimal:
        disc: True
        isoskip: True
        repos:
          - 'minimal'
          - 'BaseOS'
        variant: 'minimal'
        volname: 'dvd'
      BaseOS:
        disc: False
        isoskip: True
        variant: 'BaseOS'
        repos:
          - 'BaseOS'
          - 'AppStream'
    lorax:
      noupgrade: False
      repos:
        - 'BaseOS'
        - 'AppStream'
      variant: 'BaseOS'
      lorax_removes:
        - 'libreport-rhel-anaconda-bugzilla'
      required_pkgs:
        - 'lorax'
        - 'isomd5sum'
        - 'lorax-templates-rocky'
        - 'lorax-templates-generic'
        - 'xorriso'
  cloudimages:
    images:
      Azure:
        format: vhd
        variants: [Base, LVM]
        primary_variant: 'Base'
      EC2:
        format: qcow2
        variants: [Base, LVM]
        primary_variant: 'Base'
      GenericCloud:
        format: qcow2
        variants: [Base, LVM]
        primary_variant: 'Base'
      Container:
        format: tar.xz
        variants: [Base, Minimal, UBI]
      RPI:
        format: raw.xz
      OCP:
        format: qcow2
        variants: [Base]
      Vagrant:
        format: box
        variants: [Libvirt, Vbox, VMware]
  livemap:
    builder: "lorax"
    git_repo: 'https://git.resf.org/sig_core/kickstarts.git'
    branch: 'r10'
    ksentry:
      Workstation: rocky-live-workstation.ks
      Workstation-Lite: rocky-live-workstation-lite.ks
      XFCE: rocky-live-xfce.ks
      KDE: rocky-live-kde.ks
      MATE: rocky-live-mate.ks
      Cinnamon: rocky-live-cinnamon.ks
    allowed_arches:
      - x86_64
      - aarch64
    required_pkgs:
      - 'lorax-lmc-novirt'
      - 'vim-minimal'
      - 'pykickstart'
      - 'git'
  variantmap:
    git_repo: 'https://git.rockylinux.org/rocky/pungi-rocky.git'
    branch: 'r10'
    git_raw_path: 'https://git.rockylinux.org/rocky/pungi-rocky/-/raw/r10/'
  repoclosure_map:
    arches:
      x86_64: '--forcearch=x86_64 --arch=x86_64 --arch=athlon --arch=i686 --arch=i586 --arch=i486 --arch=i386 --arch=noarch'
      aarch64: '--forcearch=aarch64 --arch=aarch64 --arch=noarch'
      ppc64le: '--forcearch=ppc64le --arch=ppc64le --arch=noarch'
      s390x: '--forcearch=s390x --arch=s390x --arch=noarch'
    repos:
      devel: []
      BaseOS: []
      AppStream:
        - BaseOS
      CRB:
        - BaseOS
        - AppStream
      HighAvailability:
        - BaseOS
        - AppStream
      ResilientStorage:
        - BaseOS
        - AppStream
      RT:
        - BaseOS
        - AppStream
      NFV:
        - BaseOS
        - AppStream
      SAP:
        - BaseOS
        - AppStream
        - HighAvailability
      SAPHANA:
        - BaseOS
        - AppStream
        - HighAvailability
  extra_files:
    git_repo: 'https://git.rockylinux.org/staging/src/rocky-release.git'
    git_raw_path: 'https://git.rockylinux.org/staging/src/rocky-release/-/raw/r10/'
    branch: 'r10'
    gpg:
      stable: 'SOURCES/RPM-GPG-KEY-Rocky-10'
      testing: 'SOURCES/RPM-GPG-KEY-Rocky-10-Testing'
    list:
      - 'SOURCES/Contributors'
      - 'SOURCES/COMMUNITY-CHARTER'
      - 'SOURCES/EULA'
      - 'SOURCES/LICENSE'
      - 'SOURCES/RPM-GPG-KEY-Rocky-10'
      - 'SOURCES/RPM-GPG-KEY-Rocky-10-Testing'
...
