#!/usr/bin/env bash

# Source mangle vars
source $(dirname "$0")/common
# Source sync / migrate vars for repository information
source $(dirname "$0")/../sync/common

# How many 
ARG1=${1}
NUM=$(( ${ARG1:-${MIRROR_DISPLAY_COUNT}} + 2))

print_result () {
    if [[ "${result}" =~ "invalid repo or arch" ]]; then
        printf "# repo = %s arch = %s\n" "${_repo}" "${arch}"
        printf "# FAIL: invalid repo or arch\n\n"
    else
        printf "%s\n# number of mirrors returned: %s\n\n" "$( echo "$result" | head -${NUM})" "$(( $(echo "$result" | wc -l) - 2 ))"
    fi
}

cleanup_repo () {
    # plus is actually 'rockyplus'. Others may as well(?)
    if [[ "${repo}" =~ ^(plus)$ ]]; then
        repo="rocky${repo}"

    # nfv is actually 'NFV'
    elif [[ "${repo}" =~ ^(nfv)$ ]]; then
        repo="${repo^^}"
    fi

    # Everything has an 8 appended to it
    repo="${repo}-8"
    return 0
}

for repo in "${ALL_REPOS[@]}"; do 

    # Business logic must be done, sometimes...
    cleanup_repo "${repo}"

    # Print a nice header
    printf "================\n${repo}\n================\n"
    for arch in "${ARCHES[@]}" "source"; do
        # Source is treated as its own architecture
        if [[ "${arch}" == "source" ]]; then
            repo="${repo}-source"
        fi

        # Get the normal repo/arch combinations
        result=$(curl -s "${MIRRORLIST_BASE}?repo=${repo}&arch=${arch}&time&country=global")
        print_result

        # x86 and a64 have 'debug' types, as well
        if [[ "${arch}" =~ ^(x86_|aarch)64$ ]]; then
            result=$(curl -s "${MIRRORLIST_BASE}?repo=${repo}-debug&arch=${arch}&time&country=global")
            print_result
        fi
    done
    echo
done
