#!/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
FROMMAIL="Compose Tracker <releng@rockylinux.org>"
export RLVER=10
export RLREL=beta
source "/root/toolkit/sync/common"
rm -rf /etc/pungi-beta-${MAJOR}
git clone https://git.rockylinux.org/rocky/pungi-rocky.git -b r${RLVER}s /etc/pungi-beta-${MAJOR}
ret_val=$?
if [ "$ret_val" -ne 0 ]; then
  echo "Git pull failed for beta pungi config" | mutt -e "set from=\"$FROMMAIL\"" \
    -e 'set envelope_from=yes' \
    -s "Git pull on /etc/pungi-beta-${MAJOR} failed" \
    releng@rockylinux.org
  exit 1
fi
pushd /etc/pungi-beta-${MAJOR}/scripts/compose || { echo "Pungi directory not found"; exit; }
bash produce-${MAJOR}-beta-full.sh
ret_val=$?
popd || { echo "Could not go back to the previous directory"; exit; }

if [ "$ret_val" -eq 0 ]; then
  pushd /root/toolkit/sync || { echo "Toolkit directory not found"; exit; }
  RLVER=10 bash beta-release-sync-to-staging.sh
  sync_val=$?
  popd || { echo "Could not go back to previous directory"; exit; }
fi

if [ "$sync_val" -eq 0 ]; then
  DATE="$(date +%Y%m%d%H%M%S)"
  test -f /root/bin/compose_message_mm && bash /root/bin/compose_message_mm testing "Compose for ${REVISION} BETA has been synced to staging ($DATE). See the [changelogs](https://kojidev.rockylinux.org/kojifiles/compose/logs)."
fi
