#!/bin/bash

pushd /mnt/koji/compose/logs || { echo "Could not find the logs"; exit 1; }

# We'll look for 10 days instead of just 7 days.
SRCS=$(find . -maxdepth 1 -type f -mtime +10)

printf "The following will be deleted\n"
for x in $SRCS ; do echo ${x} ; done

/bin/rm ${SRCS}
popd || { echo "We couldn't leave?"; exit 1; }
