#!/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
FROMMAIL="Compose Tracker <releng@rockylinux.org>"
export RLVER=9
source "/root/toolkit/sync/common"
rm -rf /etc/pungi-lh-${MAJOR}
git clone https://git.rockylinux.org/rocky/pungi-rocky.git -b r${RLVER}s /etc/pungi-lh-${MAJOR}
ret_val=$?
if [ "$ret_val" -ne 0 ]; then
  echo "Git pull failed for LookAhead pungi config" | mutt -e "set from=\"$FROMMAIL\"" \
    -e 'set envelope_from=yes' \
    -s "Git pull on /etc/pungi-lh-${MAJOR} failed" \
    releng@rockylinux.org
  exit 1
fi
pushd /etc/pungi-lh-${MAJOR}/scripts/compose || { echo "Pungi directory not found"; exit; }
bash produce-${MAJOR}-lookahead-full.sh
ret_val=$?
popd || { echo "Could not go back to the previous directory"; exit; }

if [ "$ret_val" -eq 0 ]; then
  pushd /root/toolkit/sync || { echo "Toolkit directory not found"; exit; }
  RLVER=9 bash lh-release-sync-to-staging.sh
  popd || { echo "Could not go back to previous directory"; exit; }
fi
