#!/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
FROMMAIL="Compose Tracker <releng@rockylinux.org>"
export RLVER=8
source "/root/toolkit/sync/common"
rm -rf /etc/pungi-prod-${MAJOR}
git clone https://git.rockylinux.org/rocky/pungi-rocky.git -b "r${MAJOR}" "/etc/pungi-prod-${MAJOR}"
rm -rf /mnt/compose/8_metadata
git clone https://git.rockylinux.org/rocky/rocky-module-metadata.git -b "r${MAJOR}" /mnt/compose/8_metadata
ret_val=$?
if [ "$ret_val" -ne 0 ]; then
  echo "Git pull failed for prod pungi config" | mutt -e "set from=\"$FROMMAIL\"" \
    -e 'set envelope_from=yes' \
    -s "Git pull on /etc/pungi-prod-${MAJOR} failed" \
    releng@rockylinux.org
  exit 1
fi
pushd /etc/pungi-prod-${MAJOR}/scripts || { echo "Cron: Failed to change directory"; exit 1; }
bash updates-${MAJOR}-full.sh
ret_val=$?
popd || { echo "Cron: Could not change back to original directory"; exit 1; }

if [ "$ret_val" -eq 0 ]; then
  pushd /root/toolkit/sync || { echo "Cron: Failed to changte directory"; exit 1; }
  RLVER=8 bash sync-to-staging.sh Rocky-devel
  RLVER=8 bash sync-to-staging.sh Extras
  RLVER=8 bash sync-to-staging.sh Rocky
  popd || { echo "Cron: Could not change back to original directory"; exit 1; }

  pushd /mnt/repos-staging/mirror/pub/rocky/8.10 || { echo "Cron: Directory doesn't exist"; exit 1; }
  python3.9 /usr/local/bin/apollo_tree -p $(pwd) \
    -n 'Rocky Linux' \
    --major-version 8 \
    -i Live \
    -i Minimal \
    -i devel \
    -i extras \
    -i images \
    -i isos \
    -i live \
    -i metadata \
    -i Devel \
    -i plus \
    -i nfv
  popd || { echo "Cron: Could not change back to original directory"; exit 1; }

  pushd /root/toolkit/sync || { echo "Cron: Failed to change directory"; exit 1; }
  RLVER=8 bash sign-repos-only.sh
  popd || { echo "Cron: Could not change back to original directory"; exit 1; }
fi
