#!/bin/bash
# Reports unsigned packages for Rocky Linux 9 packages (stable)
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
export RLVER=9
FROMMAIL="Compose Tracker <releng@rockylinux.org>"
source "/root/toolkit/sync/common"
python3 /root/toolkit/mangle/koji/unsigned.py --key rocky-linux-9 --tag "dist-rocky${REVISION}" | grep '\.src' > "/tmp/unsigned_${REVISION}"
ret_val=$?

if [ "$ret_val" -ne 0 ]; then
  echo "Unable to check for unsigned builds for ${REVISION}" | mutt -e "set from=\"$FROMMAIL\"" \
    -e 'set envelope_from=yes' \
    releng@rockylinux.org
  exit 1
fi

# Assumes we got a list
sed -i 's/\.src//g' "/tmp/unsigned_${REVISION}"

mutt -e "set from=\"$FROM\"" \
  -e 'set envelope_from=yes' \
  -s "Unsigned builds for ${REVISION}" \
  releng@rockylinux.org < "/tmp/unsigned_${REVISION}"
