#!/bin/bash

pushd /mnt/compose/8 || { echo "Could not change directories"; exit 1; }

SRCS=$(find . -maxdepth 1 -type d -mtime +7 | grep -vE 'SIG-|Rocky-8.10-2024' | sort)

printf "The following will be deleted\n"
for x in $SRCS ; do echo ${x} ; done

rm -rf ${SRCS} || { echo "Could not switch back"; exit 1; }
